import type { Hotspot } from "@/components/project-demo";

export type ProjectLink = {
  label: string;
  href: string;
};

/* Where a project has got to, kept in its own slot so it reads as a state
   rather than as another fact about the work. One of a fixed set, because a
   free string drifts into marketing. */
export type Stage =
  | "Published"
  | "Preparing release"
  | "In development"
  | "Early development"
  | "Not published yet";

export type Project = {
  /* The project's address. Written down rather than derived from the
     name at request time, so a rename never silently moves a URL that is
     already in someone's history or an index. Lowercase and hyphenated;
     /projects/[slug] is generated from exactly these. */
  slug: string;
  name: string;
  descriptor: string;
  /* The <meta name="description"> for the project's own page, and nothing
     else. One per project rather than one shared line, because four pages
     answering a search with the same sentence compete with each other.
     Not rendered anywhere on the page: the panel already says all of this
     at length. */
  metaDescription: string;
  /* The project’s own mark, 256x256 in public/images. Built by
     scripts/build-project-logos.mjs, which records where each one came
     from: Rilo and Redi carry the marks they actually ship, while
     Phantom and Loxbox carry ones derived from their own design tokens,
     because neither has shipped an icon yet. */
  logo: string;
  /* Short enough to sit in the 112px rail. */
  railStatus: string;
  status: string;
  stage: Stage;
  /* Facts the prose does not already carry. Kept to two or three, and
     phrased so they stay true as the number grows rather than pinning an
     exact count that goes stale. */
  tags?: string[];
  /* The award name is fixed wording. "3rd Place, Best Use of Base44"
     is a sponsor track placement, not an overall hackathon result. */
  award?: string;
  awardEvent?: string;
  prose: string[];
  /* One line on why the thing exists at all. Kept out of prose and rendered
     last, quietest, because it is the least load-bearing thing on the page:
     a visitor who stops before it has still read everything that matters.
     Detail panel only. The home page carries prose alone and would be
     longer without being clearer. */
  why?: string;
  stack: string[];
  links: ProjectLink[];
  /* Optional still. Left unset, the entry renders as prose with no
     empty box. */
  image?: string;
  /* The interactive panel for a project. Takes the place of the still when
     present. There are no recordings any more: every project here is either
     framable live or rebuilt in the browser, and a recording of a thing the
     visitor can just use is a worse version of the thing. */
  demo?: {
    /* Set only when the app allows framing, giving a fully clickable
       embed. */
    liveUrl?: string;
    liveLabel?: string;
    /* Scales the framed page down so a tall section fits the panel in one
       view. The frame is drawn correspondingly wider and taller, so the app
       still lays out at its own desktop width. */
    liveZoom?: number;
    /* For an app whose interesting state cannot be reached by URL: a short
       numbered guide beside the frame, so a visitor knows what to click. */
    guide?: { title: string; steps: string[] };
    /* For sites that refuse to be framed: a capture of the whole page
       the visitor can scroll through in place. */
    scrollImage?: string;
    scrollImageWidth?: number;
    scrollImageHeight?: number;
    scrollLabel?: string;
    /* Generated by scripts/capture-fullpage.mjs. Puts the page’s own
       buttons back on top of the flat capture. */
    hotspots?: Hotspot[];
    /* The real page, opened in its own tab. The panel already runs the
       thing, so this is the way out to it at full size rather than a
       second copy of it. */
    pageUrl?: string;
    pageLabel?: string;
    /* The product's own flow, rebuilt and playable in the panel. For a
       product whose demo is the thing worth showing, and which a frame
       around the real page only makes smaller. */
    playable?: { component: "rilo"; label: string };
    /* Which mode the panel opens on. */
    defaultMode?: "play" | "live" | "scroll";
  };
  /* An interactive component rendered in place of a recording.
     "redi" is the app's screens rebuilt in the browser, since there is no
     public build to capture. */
  mockup?: { component: "redi"; label: string };
};

export const projects: Project[] = [
  {
    slug: "rilo",
    name: "Rilo",
    descriptor: "AI reply assistant for Gmail",
    metaDescription:
      "An AI reply assistant for Gmail, on the Chrome Web Store. Rilo reads only the email open on screen, never sends anything, and returns drafts in several tones.",
    logo: "/images/logo-rilo.webp",
    railStatus: "Live",
    status: "On the Chrome Web Store since July 2026",
    stage: "Published",
    tags: ["100+ downloads"],
    prose: [
      "Most AI email tools ask for full OAuth inbox access to read, send, and store your mail. Rilo reads only the email currently open on screen, never touches the rest of the inbox, never sends anything, and never stores your email.",
      "Each reply comes back as a few drafts across different tones and intents rather than one generic answer. Rilo was the first product I built and shipped end to end.",
    ],
    why:
      "Every AI email tool I tried wrote in its own voice, so you either sent something that didn’t sound like you or rewrote the whole thing anyway. I wanted control over how the reply actually comes out, without handing over full access to my inbox to get it.",
    stack: [
      "Next.js",
      "TypeScript",
      "Tailwind",
      "Chrome Extension APIs (Manifest V3)",
      "Firebase Auth",
      "Firestore",
      "Stripe",
      "Resend",
      "Google Gemini API",
      "Netlify",
    ],
    links: [{ label: "riloai.app", href: "https://riloai.app" }],
    image: "/images/project-rilo.webp",
    demo: {
      /* Rilo's demo section, rebuilt in place rather than framed. Framing
         the real page meant scaling a cross-origin document down far
         enough to fit, which left its body text too soft to read; the
         rebuild is the same demo at its own size and sharpness. It is
         reconstructed from the bundle riloai.app serves, so the type,
         colour, spacing, copy, motion and mascot art are Rilo's own. */
      playable: {
        component: "rilo",
        label: "Rilo's own demo, running here",
      },
      /* The way out to the real thing at full size, beside the demo
         running here. */
      pageUrl: "https://riloai.app",
      pageLabel: "Open riloai.app",
    },
  },
  {
    slug: "redi-ai",
    name: "Redi AI",
    descriptor: "Interview prep, generated per role",
    metaDescription:
      "Interview prep generated per role. Describe a job, a scholarship or a program, answer out loud, and Redi AI scores what you said, broken out by skill.",
    logo: "/images/logo-redi.webp",
    railStatus: "Mobile",
    status: "Mobile, spoken answers scored per skill",
    stage: "Not published yet",
    prose: [
      "You describe a role, whether that's a job, a scholarship, or a program, and Redi generates a question set for it. Answer out loud and it scores what you said.",
      /* The app's own coverage matrix records the questions NOT following a
         role edit (AI-7, filed, confirmed at depth), while the brief does
         rebuild around what you add. This says only the half that holds. */
      "The score comes back broken out by skill rather than as one number, and each skill is a range rather than a point, so the width of the range is how much the session actually showed. Update the role and the brief rebuilds around what you added.",
    ],
    why:
      "I’ve always been worse in interviews than I am at the thing I’m being interviewed for, and I never found a reliable way to practise. Reading question lists and answering in my head wasn’t preparation, so I built something that generates real questions for the exact role and makes you say the answers out loud.",
    stack: [
      "React Native",
      "Expo",
      "TypeScript",
      "Firebase",
      "Google Gemini API",
    ],
    links: [],
    mockup: {
      component: "redi",
      label: "The app rebuilt screen by screen, walk it",
    },
  },
  {
    slug: "phantom",
    name: "Phantom",
    descriptor: "Independent check on forest carbon credits",
    metaDescription:
      "An independent check on forest carbon credits. Phantom tests a project's claim against free public satellite data by comparing the land it protects to similar land nearby.",
    logo: "/images/logo-phantom.webp",
    railStatus: "Team build",
    status: "Environmental track",
    stage: "Published",
    award: "3rd Place, Best Use of Base44",
    awardEvent: "Ignition Hacks 2026",
    prose: [
      "Carbon credit projects claim they prevented deforestation that would otherwise have happened. Phantom checks that claim against free public satellite data by comparing the protected land to similar unprotected land nearby. If both cleared at the same rate, the credit is not buying anything.",
      "It outputs a year-by-year clearing view inside the project boundary, the project's auditor and the buyers holding its credits, and a PDF export.",
    ],
    why:
      "Carbon credits are sold on a claim that trees would have been cut down and weren’t, and almost nobody checks whether that’s true. The satellite data to check it has been free and public this whole time, which felt like the kind of gap worth closing.",
    /* Read off the repo itself (DraxAgon/IgnitionHackv7), not off the
       hackathon listing. "Base44" was never in this build: it is the
       sponsor track the placement came from, which the award line
       already carries. The app is a Vite/React SPA with a MapLibre map,
       clipping done in Turf and the report drawn client-side by jsPDF;
       the matching and synthetic-control engine beside it is Python.
       Every data source is public and keyless, and the measurements are
       committed, so the deploy is a static build on Render. */
    stack: [
      "React",
      "Vite",
      "MapLibre GL JS",
      "Turf.js",
      "jsPDF",
      "Python",
      "scikit-learn",
      "CVXPY",
      "INPE PRODES",
      "Hansen / Global Forest Watch",
      "Render",
    ],
    links: [
      {
        label: "ignitionhackv7.onrender.com",
        href: "https://ignitionhackv7.onrender.com/",
      },
    ],
    demo: {
      liveUrl: "https://ignitionhackv7.onrender.com/",
      liveLabel: "Phantom, running live",
      /* The way out to the app at full size, as on Rilo. Named rather than
         given as the host, since the deploy URL says nothing. */
      pageUrl: "https://ignitionhackv7.onrender.com/",
      pageLabel: "Open Phantom",
      /* Phantom keeps which case is open in React state. The only routes
         are #companies and #explorer, the region is a hard-coded useState
         default of "amazon", and nothing reads a query param, storage or a
         postMessage, so the Kariba view cannot be deep linked and the frame
         always lands on the Amazon list. Those entries carry an
         "Illustrative project" badge in the app itself, so rather than leave
         a visitor there, the guide walks the real one in plain language:
         switch region, open Kariba, run the verification, then check what
         it says against what actually happened to the project. */
      guide: {
        title: "Walking the Kariba case",
        steps: [
          "Region switch, top right: pick Zimbabwe. The Amazon projects the app opens on are made up examples.",
          "Open Kariba REDD+ Project. This one is real. It sold carbon credits for years on the promise that it was keeping that forest standing.",
          "On the map, orange is the land the credits cover. Red is forest inside it that has already been cut down.",
          "Drag the year slider under the map to watch the red spread, year by year.",
          "Press Run independent verification. Phantom finds unprotected land nearby that looked the same before the project started, then checks whether that land was cleared any faster.",
          "If both cleared at the same rate, the trees were coming down anyway and the credits paid for nothing. The headline is how much of what Kariba sold the satellite record cannot back up.",
          "Case study, underneath, checks that against the real record: the registry that certified Kariba found much of it unsupported, and the project left the registry in 2024.",
          "Kariba case, the switch beside it, is the same project from the buyer side.",
        ],
      },
    },
  },
  {
    slug: "loxbox",
    name: "Loxbox",
    descriptor: "Group photos, locked until reveal day",
    metaDescription:
      "Group photos locked until reveal day. Everyone adds to one shared box and nobody sees a single photo until the timer hits zero and the whole box opens at once.",
    logo: "/images/logo-loxbox.webp",
    railStatus: "Mobile",
    status: "Mobile, one shared album per group",
    /* Nobody can install it, so the stage chip and the tag still carry that
       plainly. Those two hold the state, which leaves the prose free to
       describe the product and stay true without edits rather than reading
       as a progress report that goes stale the moment anything moves. */
    stage: "Early development",
    tags: ["No public build yet"],
    prose: [
      "A group makes a box and picks a reveal date. Everyone adds photos to it and nobody sees a single one until the timer hits zero, when the whole box opens at once.",
      "The wait is the whole point. Nobody swaps their pick after seeing what everyone else put in, nobody curates the box down to the best shot in it, and the reveal lands for the whole group at the same moment.",
    ],
    why:
      "The best nights end with everyone holding a different piece of them, and those pieces mostly stay on separate phones forever. I wanted a way to put them back together, and for the photos to stay hidden long enough that people are actually present instead of performing for a feed.",
    stack: ["React Native", "Expo", "TypeScript", "Firebase"],
    links: [],
  },
];

/* The four addresses /projects/[slug] is built from, and the lookup the
   page and its share card share. A slug that is not one of these is not a
   project, which is what lets the route 404 rather than guess. */
export const projectSlugs = projects.map((project) => project.slug);

export const projectBySlug = (slug: string): Project | undefined =>
  projects.find((project) => project.slug === slug);
