import type { Hotspot } from "@/components/project-demo";

export type ProjectLink = {
  label: string;
  href: string;
};

/* Where a project has got to, kept in its own slot so it reads as a state
   rather than as another fact about the work. One of a fixed set, because a
   free string drifts into marketing. */
export type Stage =
  | "Published"
  | "Preparing release"
  | "In development"
  | "Early development"
  | "Not published yet";

export type Project = {
  name: string;
  descriptor: string;
  /* The project’s own mark, 256x256 in public/images. Built by
     scripts/build-project-logos.mjs, which records where each one came
     from: Rilo and Redi carry the marks they actually ship, while
     Phantom and Loxbox carry ones derived from their own design tokens,
     because neither has shipped an icon yet. */
  logo: string;
  /* Short enough to sit in the 112px rail. */
  railStatus: string;
  status: string;
  stage: Stage;
  /* Facts the prose does not already carry. Kept to two or three, and
     phrased so they stay true as the number grows rather than pinning an
     exact count that goes stale. */
  tags?: string[];
  /* The award name is fixed wording. "3rd Place, Best Use of Base44"
     is a sponsor track placement, not an overall hackathon result. */
  award?: string;
  awardEvent?: string;
  prose: string[];
  /* One line on why the thing exists at all. Kept out of prose and rendered
     last, quietest, because it is the least load-bearing thing on the page:
     a visitor who stops before it has still read everything that matters.
     Detail panel only. The home page carries prose alone and would be
     longer without being clearer. */
  why?: string;
  stack: string[];
  links: ProjectLink[];
  /* Optional still. Left unset, the entry renders as prose with no
     empty box. */
  image?: string;
  /* The interactive panel for a project. Takes the place of the still when
     present. There are no recordings any more: every project here is either
     framable live or rebuilt in the browser, and a recording of a thing the
     visitor can just use is a worse version of the thing. */
  demo?: {
    /* Set only when the app allows framing, giving a fully clickable
       embed. */
    liveUrl?: string;
    liveLabel?: string;
    /* Scales the framed page down so a tall section fits the panel in one
       view. The frame is drawn correspondingly wider and taller, so the app
       still lays out at its own desktop width. */
    liveZoom?: number;
    /* For an app whose interesting state cannot be reached by URL: a short
       numbered guide beside the frame, so a visitor knows what to click. */
    guide?: { title: string; steps: string[] };
    /* For sites that refuse to be framed: a capture of the whole page
       the visitor can scroll through in place. */
    scrollImage?: string;
    scrollImageWidth?: number;
    scrollImageHeight?: number;
    scrollLabel?: string;
    /* Generated by scripts/capture-fullpage.mjs. Puts the page’s own
       buttons back on top of the flat capture. */
    hotspots?: Hotspot[];
    /* The real page, opened in its own tab. The panel already runs the
       thing, so this is the way out to it at full size rather than a
       second copy of it. */
    pageUrl?: string;
    pageLabel?: string;
    /* The product's own flow, rebuilt and playable in the panel. For a
       product whose demo is the thing worth showing, and which a frame
       around the real page only makes smaller. */
    playable?: { component: "rilo"; label: string };
    /* Which mode the panel opens on. */
    defaultMode?: "play" | "live" | "scroll";
  };
  /* An interactive component rendered in place of a recording.
     "redi" is the app's screens rebuilt in the browser, since there is no
     public build to capture. */
  mockup?: { component: "redi"; label: string };
};

export const projects: Project[] = [
  {
    name: "Rilo",
    descriptor: "AI reply assistant for Gmail",
    logo: "/images/logo-rilo.webp",
    railStatus: "Live",
    status: "On the Chrome Web Store since July 2026",
    stage: "Published",
    tags: ["100+ downloads"],
    prose: [
      "Most AI email tools ask for full OAuth inbox access to read, send, and store your mail. Rilo reads only the email currently open on screen, never touches the rest of the inbox, never sends anything, and never stores your email.",
      "Each reply comes back as a few drafts across different tones and intents rather than one generic answer. Rilo was the first product I built and shipped end to end.",
    ],
    why:
      "Every AI email tool I tried wrote in its own voice, so you either sent something that didn’t sound like you or rewrote the whole thing anyway. I wanted control over how the reply actually comes out, without handing over full access to my inbox to get it.",
    stack: [
      "Next.js",
      "TypeScript",
      "Tailwind",
      "Chrome Extension APIs (Manifest V3)",
      "Firebase Auth",
      "Firestore",
      "Stripe",
      "Resend",
      "Google Gemini API",
      "Netlify",
    ],
    links: [{ label: "riloai.app", href: "https://riloai.app" }],
    image: "/images/project-rilo.webp",
    demo: {
      /* Rilo's demo section, rebuilt in place rather than framed. Framing
         the real page meant scaling a cross-origin document down far
         enough to fit, which left its body text too soft to read; the
         rebuild is the same demo at its own size and sharpness. It is
         reconstructed from the bundle riloai.app serves, so the type,
         colour, spacing, copy, motion and mascot art are Rilo's own. */
      playable: {
        component: "rilo",
        label: "Rilo's own demo, running here",
      },
      /* riloai.app now allows this origin to frame its marketing page,
         so the whole real front page runs here too: hero, the interactive
         demo, pricing, FAQ, contact. Must be the www host, since the
         apex 301s to it and a redirect would break the frame.

         The flat capture in public/media/rilo-page.webp and its
         hotspots are kept as a fallback if framing is ever withdrawn;
         re-add scrollImage here to switch back. */
      /* The fragment lands the frame on the page's own demo section rather
         than the hero, so the tab opens on the thing worth showing. */
      liveUrl: "https://www.riloai.app/#demo",
      liveLabel: "riloai.app itself, running here",
      /* The demo section is taller than the panel, so the frame is drawn wider
         and scaled down to fit it in one view. */
      liveZoom: 0.62,
      /* The way out to the real thing at full size, beside the rebuild
         and the frame. */
      pageUrl: "https://riloai.app",
      pageLabel: "Open riloai.app",
      /* Opens on the demo, which is the thing worth showing. */
      defaultMode: "play",
    },
  },
  {
    name: "Redi AI",
    descriptor: "Interview prep, generated per role",
    logo: "/images/logo-redi.webp",
    railStatus: "Mobile",
    status: "Mobile, spoken answers scored per skill",
    stage: "Not published yet",
    prose: [
      "You describe a role, whether that's a job, a scholarship, or a program, and Redi generates a question set for it. Answer out loud and it scores what you said.",
      /* The app's own coverage matrix records the questions NOT following a
         role edit (AI-7, filed, confirmed at depth), while the brief does
         rebuild around what you add. This says only the half that holds. */
      "The score comes back broken out by skill rather than as one number, and each skill is a range rather than a point, so the width of the range is how much the session actually showed. Update the role and the brief rebuilds around what you added.",
    ],
    why:
      "I’ve always been worse in interviews than I am at the thing I’m being interviewed for, and I never found a reliable way to practise. Reading question lists and answering in my head wasn’t preparation, so I built something that generates real questions for the exact role and makes you say the answers out loud.",
    stack: [
      "React Native",
      "Expo",
      "TypeScript",
      "Firebase",
      "Google Gemini API",
    ],
    links: [],
    mockup: {
      component: "redi",
      label: "The app rebuilt screen by screen, walk it",
    },
  },
  {
    name: "Phantom",
    descriptor: "Independent check on forest carbon credits",
    logo: "/images/logo-phantom.webp",
    railStatus: "Team build",
    status: "Environmental track",
    stage: "Published",
    award: "3rd Place, Best Use of Base44",
    awardEvent: "Ignition Hacks 2026",
    prose: [
      "Carbon credit projects claim they prevented deforestation that would otherwise have happened. Phantom checks that claim against free public satellite data by comparing the protected land to similar unprotected land nearby. If both cleared at the same rate, the credit is not buying anything.",
      "It outputs a year-by-year clearing view inside the project boundary, the project's auditor and the buyers holding its credits, and a PDF export.",
    ],
    why:
      "Carbon credits are sold on a claim that trees would have been cut down and weren’t, and almost nobody checks whether that’s true. The satellite data to check it has been free and public this whole time, which felt like the kind of gap worth closing.",
    stack: ["Public satellite forest-loss datasets", "Base44"],
    links: [
      {
        label: "ignitionhackv7.onrender.com",
        href: "https://ignitionhackv7.onrender.com/",
      },
    ],
    demo: {
      liveUrl: "https://ignitionhackv7.onrender.com/",
      liveLabel: "Phantom, running live",
      /* The way out to the app at full size, as on Rilo. Named rather than
         given as the host, since the deploy URL says nothing. */
      pageUrl: "https://ignitionhackv7.onrender.com/",
      pageLabel: "Open Phantom",
      /* Phantom keeps which case is open in React state. The only routes
         are #companies and #explorer, the region is a hard-coded useState
         default of "amazon", and nothing reads a query param, storage or a
         postMessage, so the Kariba view cannot be deep linked and the frame
         always lands on the Amazon list. Those entries carry an
         "Illustrative project" badge in the app itself, so rather than leave
         a visitor there, the guide walks the real one: switch region, open
         Kariba, run the verification, then check its number against what
         Verra found. */
      guide: {
        title: "Walking the Kariba case",
        steps: [
          "Region switch, top right: Zimbabwe. The app opens on the Amazon list, and every project there is marked illustrative.",
          "Open Kariba REDD+ Project. Real registered project, VCS 902, 758K ha, 26.8M credits issued since 2011.",
          "Orange is the boundary the credits are sold against, red is forest already cleared inside it.",
          "Scrub 2016 to 19 under the map to watch that clearing arrive year by year.",
          "Run independent verification. Phantom matches the parcel to unprotected land that looked the same before 2016, then reads what that land did.",
          "The headline is how much of the 26.8M the satellite record cannot support.",
          "Case study, below it, checks that against the real record: Verra’s own review found 15.2M unsupported, and Kariba left the registry in May 2024.",
          "Kariba case, beside that switch, is the same project from the buyer side.",
        ],
      },
    },
  },
  {
    name: "Loxbox",
    descriptor: "Group photos, locked until reveal day",
    logo: "/images/logo-loxbox.webp",
    railStatus: "Mobile",
    status: "Mobile, one shared album per group",
    /* Nobody can install it, so the stage chip and the tag still carry that
       plainly. Those two hold the state, which leaves the prose free to
       describe the product and stay true without edits rather than reading
       as a progress report that goes stale the moment anything moves. */
    stage: "Early development",
    tags: ["No public build yet"],
    prose: [
      "A group makes a box and picks a reveal date. Everyone adds photos to it and nobody sees a single one until the timer hits zero, when the whole box opens at once.",
      "The wait is the whole point. Nobody swaps their pick after seeing what everyone else put in, nobody curates the box down to the best shot in it, and the reveal lands for the whole group at the same moment.",
    ],
    why:
      "The best nights end with everyone holding a different piece of them, and those pieces mostly stay on separate phones forever. I wanted a way to put them back together, and for the photos to stay hidden long enough that people are actually present instead of performing for a feed.",
    stack: ["React Native", "Expo", "TypeScript", "Firebase"],
    links: [],
  },
];
