import type { Hotspot } from "@/components/project-demo";

export type ProjectLink = {
  label: string;
  href: string;
};

/* Where a project has got to, kept in its own slot so it reads as a state
   rather than as another fact about the work. One of a fixed set, because a
   free string drifts into marketing. */
export type Stage =
  | "Published"
  | "Preparing release"
  | "In development"
  | "Early development"
  | "Not published yet";

export type Project = {
  name: string;
  descriptor: string;
  /* Short enough to sit in the 112px rail. */
  railStatus: string;
  status: string;
  stage: Stage;
  /* Facts the prose does not already carry. Kept to two or three, and
     phrased so they stay true as the number grows rather than pinning an
     exact count that goes stale. */
  tags?: string[];
  /* The award name is fixed wording. "3rd Place, Best Use of Base44"
     is a sponsor track placement, not an overall hackathon result. */
  award?: string;
  awardEvent?: string;
  prose: string[];
  stack: string[];
  links: ProjectLink[];
  /* Optional still. Left unset, the entry renders as prose with no
     empty box. */
  image?: string;
  /* The interactive panel for a project. Takes the place of the still when
     present. There are no recordings any more: every project here is either
     framable live or rebuilt in the browser, and a recording of a thing the
     visitor can just use is a worse version of the thing. */
  demo?: {
    /* Set only when the app allows framing, giving a fully clickable
       embed. */
    liveUrl?: string;
    liveLabel?: string;
    /* Scales the framed page down so a tall section fits the panel in one
       view. The frame is drawn correspondingly wider and taller, so the app
       still lays out at its own desktop width. */
    liveZoom?: number;
    /* For an app whose interesting state cannot be reached by URL: a short
       numbered guide beside the frame, so a visitor knows what to click. */
    guide?: { title: string; steps: string[] };
    /* For sites that refuse to be framed: a capture of the whole page
       the visitor can scroll through in place. */
    scrollImage?: string;
    scrollImageWidth?: number;
    scrollImageHeight?: number;
    scrollLabel?: string;
    /* Generated by scripts/capture-fullpage.mjs. Puts the page’s own
       buttons back on top of the flat capture. */
    hotspots?: Hotspot[];
    /* The real page, opened in its own tab. The panel already runs the
       thing, so this is the way out to it at full size rather than a
       second copy of it. */
    pageUrl?: string;
    pageLabel?: string;
    /* Which mode the panel opens on. */
    defaultMode?: "live" | "scroll";
  };
  /* An interactive component rendered in place of a recording.
     "redi" is the app's screens rebuilt in the browser, since there is no
     public build to capture. */
  mockup?: { component: "redi"; label: string };
};

export const projects: Project[] = [
  {
    name: "Rilo",
    descriptor: "AI reply assistant for Gmail",
    railStatus: "Live",
    status: "On the Chrome Web Store since July 2026",
    stage: "Published",
    tags: ["100+ downloads"],
    prose: [
      "Most AI email tools ask for full OAuth inbox access to read, send, and store your mail. Rilo reads only the email currently open on screen, never touches the rest of the inbox, never sends anything, and never stores your email.",
      "Each reply comes back as a few drafts across different tones and intents rather than one generic answer. Rilo was the first product I built and shipped end to end.",
    ],
    stack: [
      "Next.js",
      "TypeScript",
      "Tailwind",
      "Chrome Extension APIs (Manifest V3)",
      "Firebase Auth",
      "Firestore",
      "Stripe",
      "Resend",
      "Google Gemini API",
      "Netlify",
    ],
    links: [{ label: "riloai.app", href: "https://riloai.app" }],
    image: "/images/project-rilo.webp",
    demo: {
      /* riloai.app now allows this origin to frame its marketing page,
         so the whole real front page runs here: hero, the interactive
         demo, pricing, FAQ, contact. Must be the www host, since the
         apex 301s to it and a redirect would break the frame.

         The flat capture in public/media/rilo-page.webp and its
         hotspots are kept as a fallback if framing is ever withdrawn;
         re-add scrollImage here to switch back. */
      /* The fragment lands the frame on the page's own demo section rather
         than the hero, so the panel opens on the thing worth showing. */
      liveUrl: "https://www.riloai.app/#demo",
      liveLabel: "riloai.app itself, running here",
      /* The demo section is taller than the panel, so the frame is drawn wider
         and scaled down to fit it in one view. */
      liveZoom: 0.62,
      /* The framed page carries Rilo’s own demo, so there is nothing left
         to port in beside it. All that is worth offering is the page
         itself, unframed. */
      pageUrl: "https://riloai.app",
      pageLabel: "Open riloai.app",
    },
  },
  {
    name: "Redi AI",
    descriptor: "Interview prep, generated per role",
    railStatus: "In development",
    status: "Mobile, and what I spend most of my time on now",
    stage: "Not published yet",
    tags: ["Six skills per session"],
    prose: [
      "You describe a role, whether that's a job, a scholarship, or a program, and Redi generates a question set for it. Answer out loud and it scores what you said.",
      /* The app's own coverage matrix records the questions NOT following a
         role edit (AI-7, filed, confirmed at depth), while the blurb does
         rebuild around what you add. This says only the half that holds. */
      "Update the role and Redi rebuilds it around what you added. Getting the questions themselves to follow that is the piece I am on now.",
    ],
    stack: [
      "React Native",
      "Expo",
      "TypeScript",
      "Firebase",
      "Google Gemini API",
    ],
    links: [],
    mockup: {
      component: "redi",
      label: "The app rebuilt screen by screen, walk it",
    },
  },
  {
    name: "Phantom",
    descriptor: "Independent check on forest carbon credits",
    railStatus: "Team build",
    status: "Environmental track",
    stage: "Published",
    award: "3rd Place, Best Use of Base44",
    awardEvent: "Ignition Hacks 2026",
    prose: [
      "Carbon credit projects claim they prevented deforestation that would otherwise have happened. Phantom checks that claim against free public satellite data by comparing the protected land to similar unprotected land nearby. If both cleared at the same rate, the credit is not buying anything.",
      "It outputs a year-by-year clearing view inside the project boundary, the project's auditor and the buyers holding its credits, and a PDF export.",
    ],
    stack: ["Public satellite forest-loss datasets", "Base44"],
    links: [
      {
        label: "ignitionhackv7.onrender.com",
        href: "https://ignitionhackv7.onrender.com/",
      },
    ],
    demo: {
      liveUrl: "https://ignitionhackv7.onrender.com/",
      liveLabel: "Phantom, running live",
      /* Phantom routes on #companies and #explorer only: which case is open is
         internal state, so it cannot be deep linked and the app opens on the
         Amazon list. Those entries are marked "Illustrative project" in the
         app itself, so the guide sends people to the Kariba case first, which
         is the real registered project with buyers on public record. */
      guide: {
        title: "Walking the Kariba case",
        steps: [
          "Open Kariba case, top right. The app starts on the Amazon list, and those entries are illustrative rather than real.",
          "The map is the project boundary. The orange outline is the land the credits are sold against, and red is forest already cleared inside it.",
          "Scrub 2016 to 19 under the map to watch the clearing happen year by year.",
          "Run independent verification. Phantom rebuilds the baseline from unprotected forest that looked the same before the project started.",
          "Read the result against Credits issued: 26.8M. If the comparable land cleared at the same rate, the credits bought nothing.",
        ],
      },
    },
  },
  {
    name: "Loxbox",
    descriptor: "Group photos, locked until reveal day",
    railStatus: "Early build",
    status: "Mobile, and early",
    /* The earliest thing on the page, and the chip has to say so plainly.
       "Preparing release" read as though it were a checklist away from the
       App Store. Nobody can install it, so the stage, the status line, the
       tag and the closing paragraph each say unfinished rather than leaving
       a visitor to infer it. */
    stage: "Early development",
    tags: ["No public build yet"],
    prose: [
      "A group makes a box and picks a reveal date. Everyone adds photos to it and nobody sees a single one until the timer hits zero, when the whole box opens at once.",
      "This one is early. The idea and the shape of the app are there, the rest is half built, and none of it is settled, so there is nothing to try yet and no date I would put on it.",
    ],
    stack: ["React Native", "Expo", "TypeScript", "Firebase"],
    links: [],
  },
];
