/**
 * Generates src/components/icons.ts from simple-icons.
 *
 * Icons are inlined as SVG path data so they ship with the JS, cost no
 * extra request, and inherit colour from currentColor. Re-run after
 * adding a name to ICONS below:
 *   node scripts/generate-icons.mjs
 */
import { writeFileSync } from "node:fs";
import * as si from "simple-icons";

/* label used in content -> simple-icons slug */
const ICONS = {
  GitHub: "github",
  "Next.js": "nextdotjs",
  React: "react",
  "React Native": "react",
  Expo: "expo",
  TypeScript: "typescript",
  JavaScript: "javascript",
  Python: "python",
  Firebase: "firebase",
  Stripe: "stripe",
  Tailwind: "tailwindcss",
  "Tailwind CSS": "tailwindcss",
  "Google Gemini API": "googlegemini",
  Vercel: "vercel",
  Netlify: "netlify",
  "Google Cloud Platform": "googlecloud",
  Git: "git",
  HTML: "html5",
  CSS: "css",
  Linux: "linux",
  "Android Studio": "androidstudio",
  "IntelliJ IDEA": "intellijidea",
  "Claude Code": "claude",
};

const key = (slug) => "si" + slug.charAt(0).toUpperCase() + slug.slice(1);

const entries = [];
const seen = new Set();
for (const [label, slug] of Object.entries(ICONS)) {
  const icon = si[key(slug)];
  if (!icon) {
    console.warn(`  skipped ${label} (no simple-icons entry for "${slug}")`);
    continue;
  }
  if (seen.has(label)) continue;
  seen.add(label);
  entries.push(`  ${JSON.stringify(label)}: ${JSON.stringify(icon.path)},`);
}

/* LinkedIn was withdrawn from simple-icons, so its mark is drawn here.
   Email has no brand mark and uses a plain envelope. */
const EXTRA = {
  LinkedIn:
    "M20.447 20.452h-3.554v-5.569c0-1.328-.027-3.037-1.852-3.037-1.853 0-2.136 1.445-2.136 2.939v5.667H9.351V9h3.414v1.561h.046c.477-.9 1.637-1.85 3.37-1.85 3.601 0 4.267 2.37 4.267 5.455v6.286zM5.337 7.433a2.062 2.062 0 0 1-2.063-2.065 2.064 2.064 0 1 1 2.063 2.065zm1.782 13.019H3.555V9h3.564v11.452zM22.225 0H1.771C.792 0 0 .774 0 1.729v20.542C0 23.227.792 24 1.771 24h20.451C23.2 24 24 23.227 24 22.271V1.729C24 .774 23.2 0 22.225 0z",
  Email:
    "M1.5 4.5h21a1.5 1.5 0 0 1 1.5 1.5v12a1.5 1.5 0 0 1-1.5 1.5h-21A1.5 1.5 0 0 1 0 18V6a1.5 1.5 0 0 1 1.5-1.5zm.9 2.4L12 13.2l9.6-6.3H2.4zm-.9 1.65V17.1h21V8.55l-9.6 6.3a1.5 1.5 0 0 1-1.8 0L1.5 8.55z",
};
for (const [label, path] of Object.entries(EXTRA)) {
  entries.push(`  ${JSON.stringify(label)}: ${JSON.stringify(path)},`);
}

const out = `/* GENERATED by scripts/generate-icons.mjs. Do not edit by hand.

   Brand marks from simple-icons (CC0). LinkedIn and Email are drawn
   locally: LinkedIn was withdrawn from simple-icons, and Email has no
   brand mark. Paths are 24x24 viewBox and inherit currentColor. */

export const iconPaths: Record<string, string> = {
${entries.join("\n")}
};

export function hasIcon(label: string): boolean {
  return label in iconPaths;
}
`;

writeFileSync("src/components/icons.ts", out);
console.log(`wrote src/components/icons.ts with ${entries.length} icons`);
